import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import './globals.css';
import SessionWrapper from '../components/SessionWrapper';
import TopNav from '@/components/TopNav';
import { getServerSession } from 'next-auth';
import { authOptions } from './api/auth/[...nextauth]/route';
import StoreProvider from './StoreProvider';
import { ProtectedLayout } from '@/components/protected';
import type { AppProps } from 'next/app';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'jumpLink',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const session = await getServerSession(authOptions);

  return (
    <StoreProvider>
      <html lang="en">
        <body className={inter.className}>
          <SessionWrapper session={session}>
            {session && <TopNav />}
            <div>{children}</div>
          </SessionWrapper>
        </body>
      </html>
    </StoreProvider>
  );
}
